default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  x-local_database: &x-local-database
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: render
  <<: *x-local-database

test:
  <<: *default
  database: render_test
  <<: *x-local-database

production:
  <<: *default
  database: render_pro
  url: <%= ENV['DATABASE_URL'] %>
